name: "k3se for GitHub Actions"
description: "A lightweight Kubernetes engine that deploys k3s clusters declaratively based on a cluster configuration file."
branding:
  color: gray-dark
  icon: server
inputs:
  command:
    description: "Command to execute"
    required: true
    default: up
  version:
    description: "Version of k3s to use"
    required: true
    default: latest

runs:
  using: composite
  steps:
    - name: Download binary
      shell: bash
      run: |
        if ! [ -x "$(command -v k3se)" ]; then
          mkdir -p ~/.local/bin
          docker create --name k3se ghcr.io/nicklasfrahm/k3se:${{ inputs.version }}
          docker cp k3se:/k3se ~/.local/bin
          docker rm k3se
        fi
    - name: Run k3se
      shell: bash
      run: k3se ${{ inputs.command }}
